### ISSUE TITLE
Define roles-related permissions

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/issues#129]
BobaBoard uses Roles to assign permissions to users. This sprint, we go meta: it's time to define roles-related permissions.

In particular we need to decide permissions related to:
- [ ] who is allowed to see which roles are assigned in the realms (and to whom)
- [ ] who is allowed to create roles and assign permissions to them (and if these permissions are separate)
- [ ] whether we make a separation between roles than have permissions associated with them or not
