### ISSUE TITLE
Add eslint configuration

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/issues#141]
We should add eslint to all our codebases to enforce code style conventions. Code style conventions are currently not defined very strictly, so this might involve adding common configurations, figuring out what breaks, and push people/ms boba to fix it (or add TODOs).

We should figure out what are common stylistic choices projects make and make sure that we agree on which ones we want to adopt ourselves.

```[tasklist]
### Tasks
- [ ] Discuss set of stylistic choices we need to make
- [ ] Set up eslint on boba-backend
- [ ] Review eslint configuration on boba-frontend
- [x] Review eslint configuration on boba-components
```
