### ISSUE TITLE
Move BobaBoard's codebases to this org

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/issues#77]
- [x] boba-editor
- [x] boba-components
  - [x] rename
  - [x] move
  - [x] update NPM name
- [x] boba-frontend
  - [x] check for data leaks
  - [x] change visibility
  - [x] rename
  - [x] move
- [x] boba-server
  - [x] check for data leaks
  - [x] change visibility
  - [x] rename
  - [x] move

**Comment by c-anothus** [comment]
Contributing/install docs will need to be updated with new locations.

**Comment by essential-randomness** [comment]
This has been done!
